"""food items schema

Revision ID: e9887444f151
Revises: 56ed7ead14d2
Create Date: 2026-03-29 12:55:41.374466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e9887444f151'
down_revision: Union[str, None] = '56ed7ead14d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log_items', sa.Column('food_item_id', sa.UUID(), nullable=False))
    op.add_column('log_items', sa.Column('quantity_pieces', sa.Float(), nullable=True))
    op.add_column('log_items', sa.Column('source', sa.String(), nullable=False))
    op.add_column('log_items', sa.Column('oil_used', sa.String(), nullable=True))
    op.add_column('log_items', sa.Column('oil_grams', sa.Float(), nullable=True))
    op.add_column('log_items', sa.Column('extra_ingredients', sa.JSON(), nullable=True))
    op.add_column('log_items', sa.Column('protein_g', sa.Float(), nullable=True))
    op.add_column('log_items', sa.Column('carbs_g', sa.Float(), nullable=True))
    op.add_column('log_items', sa.Column('fat_g', sa.Float(), nullable=True))
    op.add_column('log_items', sa.Column('fiber_g', sa.Float(), nullable=True))
    op.add_column('log_items', sa.Column('sugar_g', sa.Float(), nullable=True))
    op.add_column('log_items', sa.Column('sodium_mg', sa.Float(), nullable=True))
    op.add_column('log_items', sa.Column('calcium_mg', sa.Float(), nullable=True))
    op.add_column('log_items', sa.Column('iron_mg', sa.Float(), nullable=True))
    op.add_column('log_items', sa.Column('vitamin_c_mg', sa.Float(), nullable=True))
    op.add_column('log_items', sa.Column('vitamin_a_ug', sa.Float(), nullable=True))
    op.add_column('log_items', sa.Column('potassium_mg', sa.Float(), nullable=True))
    op.add_column('log_items', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'log_items', 'food_items', ['food_item_id'], ['id'])
    op.drop_column('log_items', 'food_name')
    op.drop_column('log_items', 'carbs')
    op.drop_column('log_items', 'fats')
    op.drop_column('log_items', 'protein')
    op.drop_column('log_items', 'micronutrients')
    op.add_column('meal_logs', sa.Column('total_protein_g', sa.Float(), nullable=True))
    op.add_column('meal_logs', sa.Column('total_carbs_g', sa.Float(), nullable=True))
    op.add_column('meal_logs', sa.Column('total_fat_g', sa.Float(), nullable=True))
    op.add_column('meal_logs', sa.Column('total_fiber_g', sa.Float(), nullable=True))
    op.add_column('meal_logs', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('meal_logs', 'total_fats')
    op.drop_column('meal_logs', 'total_carbs')
    op.drop_column('meal_logs', 'total_protein')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meal_logs', sa.Column('total_protein', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('meal_logs', sa.Column('total_carbs', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('meal_logs', sa.Column('total_fats', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('meal_logs', 'updated_at')
    op.drop_column('meal_logs', 'total_fiber_g')
    op.drop_column('meal_logs', 'total_fat_g')
    op.drop_column('meal_logs', 'total_carbs_g')
    op.drop_column('meal_logs', 'total_protein_g')
    op.add_column('log_items', sa.Column('micronutrients', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('log_items', sa.Column('protein', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('log_items', sa.Column('fats', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('log_items', sa.Column('carbs', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('log_items', sa.Column('food_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'log_items', type_='foreignkey')
    op.drop_column('log_items', 'created_at')
    op.drop_column('log_items', 'potassium_mg')
    op.drop_column('log_items', 'vitamin_a_ug')
    op.drop_column('log_items', 'vitamin_c_mg')
    op.drop_column('log_items', 'iron_mg')
    op.drop_column('log_items', 'calcium_mg')
    op.drop_column('log_items', 'sodium_mg')
    op.drop_column('log_items', 'sugar_g')
    op.drop_column('log_items', 'fiber_g')
    op.drop_column('log_items', 'fat_g')
    op.drop_column('log_items', 'carbs_g')
    op.drop_column('log_items', 'protein_g')
    op.drop_column('log_items', 'extra_ingredients')
    op.drop_column('log_items', 'oil_grams')
    op.drop_column('log_items', 'oil_used')
    op.drop_column('log_items', 'source')
    op.drop_column('log_items', 'quantity_pieces')
    op.drop_column('log_items', 'food_item_id')
    # ### end Alembic commands ###
